# frozen_string_literal: true

require 'fileutils'
require 'pathname'

module News
  class FileWriter
    def initialize
      @news_root = StoragePaths.news_root
      @tickers_root = StoragePaths.research_root
    end

    def write_articles(articles)
      articles.each do |article|
        path = write_article_file(article)
        article.update!(file_path: path.to_s)
        write_ticker_files(article)
      end
    end

    def write_latest_summary(articles = nil)
      summary = if articles
        build_summary_from_articles(articles)
      else
        News::LatestSummaryService.new.call
      end
      latest_path = @news_root.join('latest.md')
      FileUtils.mkdir_p(@news_root)
      latest_path.write(summary)
      summary
    end
    
    def build_summary_from_articles(articles)
      updated_at = Time.current.utc.strftime("%Y-%m-%d %H:%M UTC")
      body = +"# News Summary (HIGH impact only)\n"
      body << "Updated: #{updated_at}\n\n"
      
      if articles.empty?
        body << "*No high-impact news articles.*\n"
      else
        articles.each do |article|
          symbols = article.symbols
          symbols_str = symbols.any? ? symbols.first(3).join(", ") : "General"
          time_str = article.published_at&.strftime("%H:%M")
          body << "- **#{symbols_str}**: #{article.headline} [#{article.source} #{time_str}]\n"
        end
      end
      
      body
    end

    private

    def write_article_file(article)
      created_at = (article.published_at || article.created_at).utc
      date_dir = @news_root.join(created_at.strftime('%Y-%m-%d'))
      FileUtils.mkdir_p(date_dir)

      time_prefix = created_at.strftime('%H%M%S')
      filename = "#{time_prefix}-#{article.external_id}.md"
      filepath = date_dir.join(filename)

      symbols = article.symbols
      symbols_str = symbols.any? ? symbols.join(', ') : 'N/A'
      content = article.content_or_summary

      body = <<~MARKDOWN
        ---
        id: #{article.external_id}
        headline: "#{escape_quotes(article.headline || 'N/A')}"
        source: #{article.source || 'Unknown'}
        symbols: #{symbols.to_json}
        created: #{created_at.iso8601}
        ---

        # #{article.headline || 'No headline'}

        **Source:** #{article.source || 'Unknown'} | **Symbols:** #{symbols_str} | **Time:** #{created_at.strftime('%Y-%m-%d %H:%M:%S UTC')}

        #{content.presence || 'No content available.'}
      MARKDOWN

      filepath.write(body)
      filepath
    end

    def write_ticker_files(article)
      symbols = article.symbols
      return if symbols.empty?

      created_at = (article.published_at || article.created_at).utc
      date_str = created_at.strftime('%Y-%m-%d %H:%M')
      source = article.source || 'Unknown'
      headline = strip_html(article.headline.to_s).presence || 'No headline'
      content = strip_html(article.content_or_summary)
      content = "#{content[0, 297]}..." if content.length > 300

      entry = <<~MARKDOWN
        ### #{date_str} - #{source}
        #{headline}
        > #{content}
      MARKDOWN

      FileUtils.mkdir_p(@tickers_root)
      symbols.each do |symbol|
        next if symbol.blank?
        write_ticker_entry(symbol, entry)
      end
    end

    def write_ticker_entry(symbol, entry)
      # Sanitize ticker symbol for filesystem (BRK/A -> BRK_A)
      safe_symbol = symbol.gsub('/', '_')
      
      news_file = @tickers_root.join("#{safe_symbol}-news.md")
      research_file = @tickers_root.join("#{safe_symbol}.md")
      template_file = @tickers_root.join('_TEMPLATE.md')

      if news_file.exist?
        news_file.open('a') { |file| file.write(entry) }
      else
        header = <<~MARKDOWN
          # #{symbol} News

          <!-- AUTO-GENERATED BY NEWS SYSTEM - DO NOT EDIT -->

        MARKDOWN
        news_file.write(header + entry)
      end

      return if research_file.exist?
      return unless template_file.exist?

      content = template_file.read
      content = content.gsub('[TICKER]', symbol)
      content = content.gsub('[DATE]', Time.current.strftime('%Y-%m-%d'))
      content = content.gsub('[AGENT]', 'news-poll')
      content = content.gsub('## Recent News', "## Recent News\nSee: #{symbol}-news.md")
      research_file.write(content)
    end

    def escape_quotes(value)
      value.to_s.gsub('"', '\"')
    end

    def strip_html(value)
      ActionView::Base.full_sanitizer.sanitize(value.to_s).gsub(/\s+/, ' ').strip
    end
  end
end
