#!/usr/bin/env bash
set -euo pipefail

repo_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)
shared_root="$repo_root/agents/_shared"
check_only=0
active_agents=(tiverton weston logan gerrard danforth dundas)

if [[ "${1:-}" == "--check" ]]; then
  check_only=1
  shift
fi

render_text() {
  local agent_id="$1"
  sed -e "s|{{agent_id}}|$agent_id|g"
}

base_for_agent() {
  local agent_id="$1"
  case "$agent_id" in
    tiverton)
      printf '%s\n' "$shared_root/coordinator-base.md"
      ;;
    *)
      printf '%s\n' "$shared_root/trader-base.md"
      ;;
  esac
}

render_agent() {
  local agent_dir="$1"
  local agent_id
  local identity_file
  local base_file
  local output_file
  local tmp_file

  agent_id=$(basename "$agent_dir")
  identity_file="$agent_dir/IDENTITY.md"
  base_file=$(base_for_agent "$agent_id")
  output_file="$agent_dir/AGENTS.md"

  if [[ ! -f "$identity_file" ]]; then
    printf 'missing identity file: %s\n' "$identity_file" >&2
    return 1
  fi

  tmp_file=$(mktemp)
  {
    printf '<!-- Generated by scripts/bootstrap/render-agent-contracts.sh. Edit IDENTITY.md or agents/_shared/*.md. -->\n\n'
    render_text "$agent_id" < "$identity_file"
    printf '\n\n'
    render_text "$agent_id" < "$base_file"
    printf '\n'
  } > "$tmp_file"

  if [[ $check_only -eq 1 ]]; then
    if ! cmp -s "$tmp_file" "$output_file"; then
      printf 'out of date: %s\n' "$output_file" >&2
      rm -f "$tmp_file"
      return 1
    fi
    rm -f "$tmp_file"
    printf 'checked %s\n' "$output_file"
    return 0
  fi

  mv "$tmp_file" "$output_file"
  printf 'rendered %s\n' "$output_file"
}

if [[ $# -gt 0 ]]; then
  for agent_id in "$@"; do
    render_agent "$repo_root/agents/$agent_id"
  done
  exit 0
fi

for agent_id in "${active_agents[@]}"; do
  render_agent "$repo_root/agents/$agent_id"
done
